### ISSUE TITLE
Invalid file type warning

### ISSUE THREAD

**Issue by niksy** [squidfunk/karma-viewport#113]
## Description

Running Karma tests with this module enabled I get the following warning:

```
01 04 2019 14:36:33.724:WARN [middleware:karma]: Invalid file type, defaulting to js. json
```

### Package versions

* karma-viewport: `1.0.4`
* karma: `4.0.1`

**Comment by squidfunk** [comment]
Confirmed. Also encountered that with a newer version of Karma recently, but after some fiddling sill haven't found a fix yet. It's just a warning, so it should have no impact on functionality. Happy to merge a PR.

**Comment by niksy** [comment]
@squidfunk I think it’s related to https://github.com/squidfunk/karma-viewport/blob/3b3177eeae66b3c4d10c94f667587b187e29b7c7/src/index.ts#L92-L95, you’re pushing JSON file to `files` array and Karma doesn’t recognize it among [file types](http://karma-runner.github.io/3.0/config/files.html) it supports.

**Comment by squidfunk** [comment]
Thanks for investigating. Did you come across an idea how to silence the warning? Already tried adding it as a mime type but that didn’t do the trick.

**Comment by niksy** [comment]
Sorry, haven’t had a chance, but if adding `{ pattern: file, type: 'js' }` doesn’t work, maybe it’s something Karma related?

**Comment by sebastiangora** [comment]
When this fix will be released?

**Comment by squidfunk** [comment]
I'm sorry, i totally forgot about this! Just released [1.0.5](https://github.com/squidfunk/karma-viewport/releases/tag/1.0.5) which contains the fix.

**Comment by cerealexx** [comment]
Still happens in 1.0.7

**Comment by riteshjagga** [comment]
This isn't related to karma-viewport but want to reply as I got solution from this conversation thread and others can benefit if they land here like me.

I have test cases in CoffeeScript files which are [configured as described here](https://github.com/karma-runner/karma-coffee-preprocessor#configuration).

Had the similar issue `WARN [middleware:karma]: Invalid file type, defaulting to js. coffee` and got it fixed by using

```
files: [
  'public/javascripts/lib.js',
  {pattern: 'app/*.coffee', type: 'js'}
]
```
