### ISSUE TITLE
Is there a good way to test scrolling within the viewport?

### ISSUE THREAD

**Issue by makeros** [squidfunk/karma-viewport#32]
Hello.
I just want to test scrolling behavior on different viewport sizes.
Right now i'm scrolling viewport content with viewport.el_.contentWindow.scrollTo(0,101). But then i need also to reset scrollTop after each test.
I'm just curious if there is a better approach for this.

**Comment by squidfunk** [comment]
Thanks for your thoughts. Currently there's no way. I have to think about if it makes sense including this into the codebase.

**Comment by squidfunk** [comment]
This is finally implemented in #34 - there's a new method called `offset` that proxies calls to the content window:

``` js
viewport.offset(0, 10) // scroll 10px down
```

Scroll offset is also reset when `reset` is called. Should be ready soon.

**Comment by squidfunk** [comment]
Released as part of 1.0.0.
