### ISSUE TITLE
404 for adapter sourcemap.

### ISSUE THREAD

**Issue by altearius** [squidfunk/karma-viewport#457]
## Description

When using Karma's debug runner, the Chrome devtools makes a request to load the adapter.js file's sourcemap, `adapter\index.js.map`.

The `adapter\index.js.map` file has not been included as one of the files that Karma is allowed to serve, so this generates a 404 error, both in the Chrome dev tools and in the Karma log.

### Expected behavior

No 404 should occur and the sourcemap should load successfully.

### Actual behavior

A 404 error is generated in the Chrome dev tools:

![image](https://user-images.githubusercontent.com/270430/86261908-2e500380-bb8d-11ea-90f7-979716a5dd1b.png)

And in the Karma log:

![image](https://user-images.githubusercontent.com/270430/86261970-44f65a80-bb8d-11ea-9762-a48ea63028d8.png)

### Steps to reproduce the bug

1. Open Karma in "Watch" mode with Chrome.
2. In the Chrome tab, click "Debug" to open the Karma debug runner.
3. Press F12 to open the Chrome Dev Tools.  This triggers the request to the source map.
4. Observe the 404 error.

### Package versions

* karma-viewport: `1.0.6`
* karma: `4.4.1`

### System information

* OS: Windows 10
* Chrome `83.0.4103.116`

**Comment by squidfunk** [comment]
Fixed by #458.

**Comment by squidfunk** [comment]
Released as part of 1.0.7.
