### ISSUE TITLE
No window resize event is triggered

### ISSUE THREAD

**Issue by hornta** [squidfunk/karma-viewport#555]
Cab we have window resize event to be triggered when the size of changed?

**Comment by squidfunk** [comment]
Thanks for your issue. Could you please elaborate on what you want to achieve and what doesn't work?

**Comment by hornta** [comment]
Hi. I solved my problem bu judt triggering a resize event after I changed the viewport size. I initially thought karma-viewport was already dispatching a resize event but I guess I could just do it myself.

**Comment by squidfunk** [comment]
`karma-viewport` runs your tests in an `iframe` and resizes the `iframe`:

https://github.com/squidfunk/karma-viewport/blob/869d82c53f6a5113f8fd0e6ded50c6a468f57be8/src/adapter/viewport.ts#L200-L203

We could dispatch a custom `resize` event, as I'm not sure if there's an easier solution.
